name: "Install dependencies"
description: "Composite action to install dependencies of the python microservice"
runs:
  using: composite
  steps:
    #- uses: actions/checkout@v4
      #with:
        #repository: 'mtararujs/python-greetings'
        #path: ./python-greetings

    - name: Info OS
      run: echo "Python prerequisites on Linux"
      shell: bash    
    - name: Setup prerequisites #THIS IS HIGHLY SPECIFIC TO LINUX AND PYTHON VERSION
      working-directory: ./python-greetings
      run: |
        python3 -m venv venv
        source venv/bin/activate
    - name: Info python
      run: echo "Installing dependencies"
      shell: bash
    - name: Install depends
      working-directory: ./python-greetings
      run: pip install -r requirements.txt
      #run: pip install -r requirements.txt
      shell: bash