name: "Install dependencies"
description: "Composite action to install dependencies of the python microservice"
runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
    - uses: actions/checkout@v4
      with:
        repository: 'mtararujs/python-greetings'
        path: ./python-greetings

    - name: Info OS
      run: echo "Python prerequisites on Linux"
      shell: bash    
    - name: Setup prerequisites #THIS IS HIGHLY SPECIFIC TO LINUX AND PYTHON VERSION
      working-directory: /python-greetings
      run: |
        RUNNER_TRACKING_ID="" && python3 -m venv venv
        RUNNER_TRACKING_ID="" && source venv/bin/activate
        ls -a
      shell: bash
    - name: Info python
      run: echo "Installing dependencies"
      shell: bash
    - name: Install depends
      working-directory: /python-greetings
      run: RUNNER_TRACKING_ID="" && venv/bin/pip install -r requirements.txt #RUNNING PIP IN A VIRTUAL ENVIRONMENT IS REQUIRED FOR LINUX
      #run: pip install -r requirements.txt
      shell: bash