name: "Install dependencies"
description: "Composite action to install dependencies of the python microservice"
runs:
  using: composite
  steps:
    #- uses: actions/checkout@v4
      #with:
        #repository: 'mtararujs/python-greetings'
        #path: ./python-greetings
        
    - name: Info
      run: echo "Installing dependencies"
      shell: bash
    - name: Install depends
      working-directory: ./python-greetings
      run: pipx install -r requirements.txt
      shell: bash